#!/usr/bin/bash

# install all files to ~ by symlinking them,
# this way, updating them is as simple as git pull
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: May 25, 2012
# License: MIT

# Run tests first to ensure .env file is valid
if [ -f ./tests ]; then
	./tests
	if [ $? -ne 0 ]; then
		echo "Error: Tests failed. Please fix the issues before proceeding."
		exit 1
	fi
else
	echo "Error: tests not found. Please ensure it exists in the current directory."
	exit 1
fi

# Create default ssh config file
if [ -f ./default_ssh_config ]; then
	./default_ssh_config
else
	echo "Error: default_ssh_config not found. Please ensure it exists in the current directory."
	exit 1
fi

# Source .env file
if [ -f ./.env ]; then
	. ./.env
else
	echo "Error: .env file not found. Please create it before running the script."
	exit 1
fi

if [ -f ./helpers/compare_files ]; then
	. ./helpers/compare_files
else
	echo "Error: compare_files file not found. Please ensure it exists in the current directory."
	exit 1
fi

if [ -f ./helpers/setup_crontab ]; then
	. ./helpers/setup_crontab
else
	echo "Error: setup_crontab file not found. Please ensure it exists in the current directory."
	exit 1
fi

# makes "defaults" command print to screen
defaults() {
	echo defaults "$@"
	command defaults "$@"
}

# verbose ln, because `ln -v` is not portable
symlink() {
	printf '%55s -> %s\n' "${1/#${HOME}/\~}" "${2/#${HOME}/\~}"
	ln -nf "$@"
}

# Create array of files to link
dotfiles=($(find ./files/* -maxdepth 1 -type f ! -type d -printf '%f\n'))

# Link dotfiles
for f in "${dotfiles[@]}"; do
	if [[ "${f}" == "conkyrc" ]]; then
		# Skip conkyrc if conky is not installed
		if ! command -v conky &> /dev/null; then
			echo "Conky is not installed, skipping conkyrc symlink."
			continue
		fi
	fi
	# Check if a directory with file name exists and a symlink doesn't exist
	[[ -d ~/."${f}" && ! -L ~/."${f}" ]] && rm -r ~/."${f}"
	# Check file exists in files directory
	[[ -f ./files/"${f}" ]] && symlink "${PWD}/files/${f}" /home/${USER}/."${f}"
done

# Create array of folders to link
dotfolders=($(find ./files/* -maxdepth 1 -type d ! -type f -printf '%f\n'))

# Link dotfolders
for f in "${dotfolders[@]}"; do
	# Create array of files in folder
	if [[ "${f}" == "duckdns" && ! -n ${DUCK_TOKEN} ]]; then
		continue
	fi
	folder_files=($(find ./files/"${f}"/* -maxdepth 1 -type f ! -type d -printf '%f\n'))
	#Check if folder exists in files directory, and doesn't exist in home directory
	[[ -d ./files/"${f}" ]] && ! [[ -d "/home/${USER}/.${f}" ]] && mkdir "/home/${USER}/.${f}"
	# check if directory exists in home directory
	[[ -d "/home/${USER}/.${f}" ]] && for file in "${folder_files[@]}"; do
		# Check file exists in files directory
		[[ -f ./files/"${f}"/"${file}" ]] && symlink "${PWD}/files/${f}/${file}" /home/${USER}/."${f}"/"${file}"
	done
done

# Set up user as sudoer without password
echo "$USER ALL=(ALL:ALL) NOPASSWD: ALL" | sudo tee "/etc/sudoers.d/dont-prompt-${USER}-for-sudo-password" > /dev/null

# Set up crontab
setup_crontab

# Copy .env file to local servers and id files
for server in "${LOCAL_SERVERS[@]}"; do
	if [[ -z "${server}" || "${server}" == $(hostname) ]]; then
		continue
	fi

	# Check and copy ssh keys first
	if compgen -G "/home/${USER}/.ssh/*.pub" > /dev/null; then
		if ! ssh -o PasswordAuthentication=no ${server} /bin/true; then
			ssh-copy-id -i /home/${USER}/.ssh/*.pub "${server}" &> /dev/null && echo "SSH keys copied to ${server}"
		else
			echo "SSH keys already exist on ${server}, skipping..."
		fi
	else 
		echo "NO SSH keys found, please create them first"
	fi

	# Compare env files, this is problematic as if you run this on a sever with old env files
	# It will overwrite the new ones and break things
	if compare_files "./.env" "~/dotfiles/.env" "${server}" ; then
		echo ".env file is already up to date on ${server}, skipping copy."
	else 
		echo "Copying .env file to ${server}..."
		scp .env "${server}":~/dotfiles/.env > /dev/null && echo ".env file copied to ${server}"
	fi


done
